version: "3"

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./storage:/storage
    environment:
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage
